

server:
  port: 8765


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#数据源配置
spring:
  application:
    name: user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/zstedu?useUnicode=true&useOldAliasMetadataBehavior=true
      &characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    druid:

      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200



mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #classpath*: "com/dcmsforum/dao/mapper/*Mapper.xml"
  #classpath: mybatis/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.zstedu.user.mapper
  # typeEnumsPackage: com.baomidou.springboot.db.entity.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: Y
      logic-not-delete-value: N
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
